#%RAML 1.0 NamedExample
#example:

<?xml version="1.0" encoding="UTF-8"?>
<root>
   <base>EUR</base>
   <date>2019-09-25</date>
   <rates>
      <AUD>1.6236</AUD>
      <BGN>1.9558</BGN>
      <BRL>4.5987</BRL>
      <CAD>1.458</CAD>
      <CHF>1.0841</CHF>
      <CNY>7.8239</CNY>
      <CZK>25.867</CZK>
      <DKK>7.4648</DKK>
      <GBP>0.88668</GBP>
      <HKD>8.6059</HKD>
      <HRK>7.406</HRK>
      <HUF>334.95</HUF>
      <IDR>15539.53</IDR>
      <ILS>3.8482</ILS>
      <INR>78.0215</INR>
      <ISK>136</ISK>
      <JPY>118</JPY>
      <KRW>1318.39</KRW>
      <MXN>21.5068</MXN>
      <MYR>4.6015</MYR>
      <NOK>9.931</NOK>
      <NZD>1.7435</NZD>
      <PHP>57.475</PHP>
      <PLN>4.3915</PLN>
      <RON>4.7438</RON>
      <RUB>70.6879</RUB>
      <SEK>10.6825</SEK>
      <SGD>1.5133</SGD>
      <THB>33.577</THB>
      <TRY>6.2598</TRY>
      <USD>1.0982</USD>
      <ZAR>16.5085</ZAR>
   </rates>
</root>