#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/a53bef97-6377-4df7-9155-e3ac5b2535f5/ # 
version: v1
title: forexApi

/currencyconversion:
  get:
    queryParameters:
      baseCcy:
        type: string
        required: false
      targetCcy:
        type: string
        required: false
      outputType:
        type: string
        required: false
        example: !include AllCurrencyExampleXML.raml

    responses:
     200:
       body:
         application/json:
           example: !include AllCurrencyExampleJSON.raml
         application/xml:
           example: !include AllCurrencyExampleXML.raml
         

  /baseCcy:    
    /{baseCurrency}:
      get:
        responses:
          200:
            body:
              application/json:
                example: !include UriParamExample.raml
              application/xml:

      /outputType:
            /{oType}:
                get:
                  responses:
                    200:
                      body:
                        application/xml:
                          example: !include AllCurrencyExampleXML.raml
                        application/json:
          
      /targetCcy:
        /{targetCurrency}:
          get:
            responses:
              200:
                body:
                  application/json:
                    example: !include UriParamExample.raml
                  application/xml:
          
          /outputType:
            /{oType}:
                get:
                  responses:
                    200:
                      body:
                        application/xml:
                          example: !include AllCurrencyExampleXML.raml
                        application/json:
              
      